version: "3.7"
services:
  lms-api:
    build: .
    image: eu.gcr.io/kettenbach-it/lms-flask-api:1.0.3
    container_name: lms-api
    networks:
      default:
        ipv4_address: 192.168.204.108
    restart: always
    environment:
      LMS_HOST: lms.wi.kettenbach-it.de
      LMS_PORT: 9090


networks:
  default:
    external:
      name: lan

